### PR TITLE
Update manifest and README for 1.2.4 release

### PR DESCRIPTION
**Pull request by magikcypress**
Update source for fix security XSS issue with CSS styles inside an SVG tag.

https://roundcube.net/news/2017/03/10/updates-1.2.4-and-1.1.8-released

Since this PR has been rerouted from master to testing. It passes to a minor decision.
- [ ] **Upgrade previous version** : 
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 
- [ ] **CI succeeded** : 
When the PR is mark as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
I've just tested it.

Your cheksum is wrong, need to be 76b52a6405e0fc36b6829bf21200badbc681b18c95c7b3d9098e90f9de7ed9cc.

And you have an error with the patch file.
```
Hunk #2 FAILED at 38.
Hunk #3 FAILED at 80.
2 out of 3 hunks FAILED -- saving rejects to file bin/installto.sh.rej
```

So it doesn't work.

**Comment by maniackcrudelis** [comment]
Now, the checksum is ok. But you still have an error with the upgrade.
The upgrade script freeze and timeout.

**Comment by magikcypress** [comment]
This app is broken on testing too. Need more refactoring.

**Comment by maniackcrudelis** [comment]
Fixed by https://github.com/YunoHost-Apps/roundcube_ynh/pull/13

**Pull request closed without merging**
