### PR TITLE
Testing + fix Buster

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem

Install fails on buster because there's no php-mcrypt anymore

## Solution

After a quick lookup on the internet, my understanding is that the stuff provided by php-mcrypt is old / deprecated since a while, and in fact Roundcube doesnt need it anymore (it was added back to the jessie or maybe even squeeze era).

So let's remove it. (N.B. : I haven't tested anything though - but it should be okay to commit this for stretch as well)

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Kay0u
- [x] **Approval (LGTM)** : Kay0u
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/roundcube_ynh%20PR79/)  

When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by alexAubin** [comment]
Uh in fact that's not the only dependency not available on Buster ...

There's also php-net-ldap2 and php-net-ldap3 ... Maybe they aren't needed either - naively if stuff are installed via composer right now, maybe these are part of what's installed ... But I don't know enough about Composer.

**Comment by maniackcrudelis** [comment]
Just tried to install on buster, it works as expected. Didn't try everything but at least the app seems to work normally.

But... on the same buster, package completely failed the install...

**Comment by maniackcrudelis** [comment]
Fix for buster, tested on Buster and Stretch.
Although I've never seen my ldap contacts... (But I don't either with my current installation on my own server...)

@kay0u @alexAubin if you have anything to say about it.
Otherwise I suggest to merge in 3 days.

**Comment by kay0u** [comment]
Yup, same for me... ok to merge it in 3 days

**Pull request merged**
