### PR TITLE
Upgrade to 1.5.0

### PR DESCRIPTION
**Pull request by ericgaspar**
- *Upgrade to 1.5.0*
- *Enigma installed by default* #116
- *Protect config file* #110 
- Upgrade contextmenu_version to 3.2.1

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by alexAubin** [comment]
Let's merge in testing and try to move to merging this in master ?

**Pull request merged**
