### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
- *The application is not up-to-date*

## Solution
- *Upgrade to latest version 1.3.9*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : Maniack C
- [x] **Approval (LGTM)** : Kay0u
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/roundcube_ynh%20PR57/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by zamentur** [comment]
There is an important bug in master version (see https://forum.yunohost.org/t/roudcube-bouton-envoye-innactif-postfix-connection-refused/7614/11 ) I suggest to keep this testing small as possible to merge it quickly

**Comment by zamentur** [comment]
I have reviewed the code. It seems ok.

**Comment by zamentur** [comment]
For a strange reason install on subpath fail:
https://ci-apps-hq.yunohost.org/jenkins/job/roundcube_ynh%20PR57/1/console

**Comment by maniackcrudelis** [comment]
Looks like that PR has been forgotten. Or maybe it was on purpose?

Ready to be reviewed, if @JimboJoe agree.

**Comment by JimboJoe** [comment]
I do agree :wink:

**Comment by maniackcrudelis** [comment]
I was asking mainly because I think we do not have any feedback from this testing.

**Comment by JimboJoe** [comment]
@zamentur the forum post [here](https://forum.yunohost.org/t/official-app-roundcube/3965/27?u=jimbojoe) doesn't seem so positive about this upgrade...

**Comment by kay0u** [comment]
Can be merged in 3 days

**Comment by alexAubin** [comment]
Bump folks, apparently this could be merged in 3 days, 15 days ago ? (Can I click the button :eyes: ? )

**Comment by kay0u** [comment]
Sorry, but this is MY button.

**Comment by JimboJoe** [comment]
@kay0u The button to post about the stable release in the roundcube dedicated thread on the forum is yours as well, I presume... :stuck_out_tongue_winking_eye:

**Comment by kay0u** [comment]
It's done, sorry I never pushed that button before *.*

**Pull request merged**
