### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
- Update to 1.5.2

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by pp-r** [comment]
Hello,

I've just try another upgrade but it failed to :
https://paste.yunohost.org/raw/bovohuhije

ppr

**Comment by alexAubin** [comment]
Naively LGTM but I don't know how that's supposed to fix what you were discussing in https://github.com/YunoHost-Apps/roundcube_ynh/issues/126#issuecomment-1001224758 :thinking:

**Comment by ericgaspar** [comment]
This PR upgrade the version to upstream. #126 is still to be fixed.

**Pull request merged**
