### PR TITLE
Update php-fpm.conf

### PR DESCRIPTION
**Pull request by ericgaspar**
#141

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by grenagit** [comment]
You just have to rename the extra config `php-fpm.conf` to `extra_php-fpm.conf` to make it functional :+1:

**Comment by ericgaspar** [comment]
> You just have to rename the extra config `php-fpm.conf` to `extra_php-fpm.conf` to make it functional 👍

of course, thanks

**Comment by ericgaspar** [comment]
!testme

**Comment by grenagit** [comment]
I’m surprised that this branch is not merge in the latest version of the app 😕
I have been using this branch on my server for several weeks without any problem 👍

**Comment by ericgaspar** [comment]
> I’m surprised that this branch is not merge in the latest version of the app 😕 

You shouldn't. This branch is waiting to be reviewed...

**Review by tituspijean — APPROVED** [review]

**Pull request merged**
