### PR TITLE
Upgrade to upstream 1.4.1

### PR DESCRIPTION
**Pull request by bhdouglass**
## Problem

~There is an RC out with the latest version of RoundCube. Since it's not yet a stable release I don't expect this PR to be merged yet, but I wanted to get this out there so people can try out the latest version (the new theme is awesome!) and I can get some feedback on the PR so it's ready for the full release of 1.4.0.~

Version 1.4.1 has been released!

## Solution

Updated to the latest 1.4.1

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : JimboJoe
- [x] **Approval (LGTM)** : JimboJoe
- [x] **Approval (LGTM)** : frju365
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/roundcube_ynh%20PR67/)  

When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by JimboJoe** [comment]
Roundcube 1.4.0 [is out](https://roundcube.net/news/2019/11/09/roundcube-1.4.0-released)!
It could also take benefit from the use of redis cache (as Nextcloud or Wallabag YunoHost packages already do).

**Comment by JimboJoe** [comment]
@bhdouglass Do you think you can find time to adapt your PR?

**Comment by bhdouglass** [comment]
Yep! I'll try an push up an update today or tomorrow. I'll leave redis for another PR 👍

**Comment by bhdouglass** [comment]
@JimboJoe this should be good to go now!

**Comment by JimboJoe** [comment]
Working OK when upgrading from previous version, except when going to PGP keys configuration:

As I'm not a user, I don't know if it's a new problem, though

**Comment by bhdouglass** [comment]
@JimboJoe did you previously have PGP setup?

**Comment by bhdouglass** [comment]
@JimboJoe I believe I fixed the upgrade issue (not sure how to test that, any pointers?). Also I updated it to 1.4.1

**Comment by JimboJoe** [comment]
The fix is  working, thanks! :+1:

**Comment by frju365** [comment]
Let's merge it in three days. (I check the old PR :-/ )

**Pull request merged**
