### PR TITLE
Added dependencies php-gd php-mbstring

### PR DESCRIPTION
**Pull request by anmol26s**
## Problem
- *I had problem installing the app https://github.com/YunoHost-Apps/roundcube_ynh/issues/36 .  I solved it that time(I don't remember how). Now a user have same problem and provide with a solution of missing dependencies php-gd php-mbstring.*

## Solution
- *So adding them.*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Maniack C
- [x] **Approval (LGTM)** : Maniack C
- [x] **Approval (LGTM)** : JimboJoe
- **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/roundcube_ynh%20PR42%20(Official_fork)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Code review Ok, after fix though

**Comment by JimboJoe** [comment]
Thanks for this!
@anmol26s Could you please possibly modify the check_process file to update the commit reference for the "Upgrade from previous version" to a reference which was compatible with Stretch (the CI is failing on this)?
Thanks!

**Comment by anmol26s** [comment]
@JimboJoe 
Is this ok now?

**Comment by JimboJoe** [comment]
Fine, thanks!
Will be merged in 3 days.

**Pull request merged**
