### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
- *Install is broken on stretch*

## Solution
- *Add php-zip as a dependence and remove jessie-backports*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Maniack C (from #35)
- [x] **Approval (LGTM)** : Josué (from #35)
- [x] **Approval (LGTM)** : Maniack C (from #35)
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/roundcube_ynh%20testing%20(Official)/)

When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by JimboJoe** [comment]
Well, I'm OK with exceptionally reducing testing period, provided there's only one contributing PR and that we already have several good reports on it on the forum. What about merging in 3 days... ?

**Comment by maniackcrudelis** [comment]
Agree, I read that you want to release a stable for stretch soon. So, let's go forward with this stretch fix

**Comment by alexAubin** [comment]
Bumpity bump :D

**Comment by frju365** [comment]
Well, let's merge !

**Pull request merged**
