### PR TITLE
testing

### PR DESCRIPTION
**Pull request by ericgaspar**
- Upgrade to version 1.6.0

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Review by yalh76 — APPROVED** [review]

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Review by tituspijean — COMMENTED** [review]
Upgrade from 1.5.3 fails: https://paste.yunohost.org/raw/jokasaqote

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Review by tituspijean — APPROVED** [review]

**Pull request merged**
