### PR TITLE
Add Calendar plugin

### PR DESCRIPTION
**Pull request by ericgaspar**
#140

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by tituspijean** [comment]
I'm getting the same warnings as the CI:

```
Warning: ERROR: Failed to load plugin file /var/www/roundcube/plugins/calendar/calendar.php
Info: [##################+.] > Updating roundcube core...
Warning: ERROR: Failed to load plugin file /var/www/roundcube/plugins/calendar/calendar.php
Warning: Executing database schema update.
Warning: NOTICE: Update dependencies by running `php composer.phar update --no-dev`
Warning: This instance of Roundcube is up-to-date.
Warning: Have fun!
```

The plugin is indeed not loaded.

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Pull request closed without merging**
